// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using WebApi.DataBaseMegaLinea.Models;

namespace WebApi.DataBaseMegaLinea.Context
{
    public partial interface IMegaLineaContextProcedures
    {
        Task<List<SPConsultarUsuariosResult>> SPConsultarUsuariosAsync(string NtUser, int? IdArea, string Nombre, int? Activo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spLoginResult>> spLoginAsync(string IdProveedor, string Contrasenia, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
