// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApi.DataBaseMegaLinea.Models
{
    public partial class SPConsultarUsuariosResult
    {
        public int Id_usuario { get; set; }
        public string Nombre { get; set; }
        public string NTuser { get; set; }
        public string Nombre_Rol { get; set; }
        public string Area { get; set; }
        public string Cargo { get; set; }
        public bool? Activo { get; set; }
        public bool? AccesoConsulta { get; set; }
        public string FirmaUsuario { get; set; }
        public int? Id_Cargo { get; set; }
        public int? Id_area { get; set; }
        public int? Id_rol { get; set; }
        public int? IdTipoAdministrador { get; set; }
        public string TipoAdministrador { get; set; }
        public string Cedula { get; set; }
    }
}
